# Generated by Django 4.0.4 on 2022-07-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feriados',
            new_name='Feriado',
        ),
    ]
