# Generated by Django 4.0.4 on 2022-07-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('feriado', '0002_rename_feriados_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='endereco',
            field=models.ManyToManyField(to='endereco.cidade'),
        ),
    ]
