# Generated by Django 4.0.4 on 2022-07-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0003_feriado_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriado',
            name='nome',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
