# Generated by Django 4.0.4 on 2022-07-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('feriado', '0004_feriado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriado',
            name='endereco',
            field=models.ManyToManyField(blank=True, default='feriado en todo territorio <django.db.models.fields.CharField>', null=True, to='endereco.cidade'),
        ),
    ]
