# Generated by Django 4.0.4 on 2022-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('feriado', '0007_alter_feriado_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feriado',
            old_name='endereco',
            new_name='cidade',
        ),
        migrations.AddField(
            model_name='feriado',
            name='estado',
            field=models.ManyToManyField(blank=True, to='endereco.estado'),
        ),
    ]
