# Generated by Django 4.0.4 on 2022-07-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0008_rename_endereco_feriado_cidade_feriado_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feriado',
            old_name='cidade',
            new_name='cidades',
        ),
        migrations.RenameField(
            model_name='feriado',
            old_name='estado',
            new_name='estados',
        ),
    ]
