# Generated by Django 4.0.4 on 2022-07-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriado', '0009_rename_cidade_feriado_cidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriado',
            name='estados',
        ),
    ]
