# Generated by Django 4.0.4 on 2022-05-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('intervalo', models.TimeField(blank=True, null=True)),
                ('retorno', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('servidor', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
            ],
        ),
    ]
