# Generated by Django 4.0.4 on 2022-05-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('entrada', models.TimeField()),
                ('intervalo', models.TimeField()),
                ('retorno', models.TimeField()),
                ('saida', models.TimeField()),
            ],
        ),
    ]
