# Generated by Django 4.0.4 on 2022-05-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='servidor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
