# Generated by Django 4.0.4 on 2022-05-03 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0003_remove_servidor_ponto'),
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='servidor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
