# Generated by Django 4.0.4 on 2022-05-03 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0003_remove_servidor_ponto'),
        ('ponto', '0002_ponto_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='intervalo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='retorno',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='servidor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
