# Generated by Django 4.0.4 on 2022-05-03 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='ponto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ponto.ponto'),
        ),
    ]
