# Generated by Django 4.0.4 on 2022-05-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='CPF',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
