# Generated by Django 4.0.4 on 2022-05-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_servidor_ponto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='ponto',
        ),
    ]
