# Generated by Django 4.0.4 on 2022-05-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_alter_servidor_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='matricula',
        ),
        migrations.AddField(
            model_name='servidor',
            name='setor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('CONC', 'CONCURSADO'), ('CONT', 'CONTRATADO'), ('CARG', 'CARGO.COMISSION'), ('EFET', 'EFET.COMISSIONA'), ('PENS', 'PENSIONISTA'), ('CARGE', 'CARGO ELETIVO'), ('INAT', 'INATIVO'), ('PENS', 'PENSAO POR MORT'), ('SERV', 'SERVIDOR CEDIDO')], max_length=5, null=True),
        ),
    ]
