# Generated by Django 4.0.4 on 2022-06-12 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import servidor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servidor', '0003_remove_servidor_cpf_remove_servidor_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('descricao', models.TextField()),
                ('upload', models.FileField(upload_to=servidor.models.user_directory_path)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
