# Generated by Django 4.0.4 on 2022-06-12 01:55

from django.db import migrations, models
import servidor.models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0004_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=servidor.models.user_directory_path),
        ),
    ]
