# Generated by Django 4.0.4 on 2022-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0005_alter_justificativa_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativa',
            name='status',
            field=models.CharField(choices=[('PEN', 'PENDENTE'), ('APR', 'APROVADO'), ('REP', 'REPROVADO')], default='PEN', max_length=3),
        ),
    ]
