# Generated by Django 4.0.4 on 2022-06-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0007_rename_upload_justificativa_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificativa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='justificativa',
            name='servidor',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
