# Generated by Django 4.0.4 on 2022-06-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0008_remove_justificativa_usuario_justificativa_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='servidor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
