# Generated by Django 4.0.4 on 2022-06-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0009_alter_justificativa_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor'),
        ),
    ]
