# Generated by Django 4.0.4 on 2022-06-21 01:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0010_alter_justificativa_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativa',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
