# Generated by Django 4.0.4 on 2022-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('intervalo', models.TimeField(blank=True, null=True)),
                ('retorno', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
