# Generated by Django 4.0.4 on 2022-05-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='intervalo',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='retorno',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='saida',
        ),
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('SEG', 'SEGUNDA'), ('TER', 'TERÇA'), ('QUA', 'QUARTA'), ('QUI', 'QUINTA'), ('SEX', 'SEXTA'), ('SAB', 'SABADO'), ('DOM', 'DOMINGO')], max_length=100)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('intervalo', models.TimeField(blank=True, null=True)),
                ('retorno', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.secretaria')),
            ],
        ),
    ]
