# Generated by Django 4.0.4 on 2022-06-21 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_remove_secretaria_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.secretaria')),
            ],
        ),
    ]
