# Generated by Django 4.0.4 on 2022-06-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_macpermitido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MacPermitido',
        ),
    ]
