# Generated by Django 4.0.4 on 2022-05-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('intervalo', models.TimeField(blank=True, null=True)),
                ('retorno', models.TimeField(blank=True, null=True)),
                ('saida', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domingos', to='horario.dia')),
                ('quarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartas', to='horario.dia')),
                ('quinta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quintas', to='horario.dia')),
                ('sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabados', to='horario.dia')),
                ('segunda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundas', to='horario.dia')),
                ('servidor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servidor.servidor')),
                ('sexta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sextas', to='horario.dia')),
                ('terca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tercas', to='horario.dia')),
            ],
        ),
    ]
