# Generated by Django 4.0.4 on 2022-05-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_alter_semana_domingo_alter_semana_quarta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semana',
            name='domingo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domingos', to='horario.dia'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='quarta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quartas', to='horario.dia'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='quinta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quintas', to='horario.dia'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='sabado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabados', to='horario.dia'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='segunda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segundas', to='horario.dia'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='sexta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sextas', to='horario.dia'),
        ),
        migrations.AlterField(
            model_name='semana',
            name='terca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tercas', to='horario.dia'),
        ),
    ]
