# Generated by Django 4.0.4 on 2022-05-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0003_alter_semana_domingo_alter_semana_quarta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dia',
            old_name='nome',
            new_name='dia',
        ),
        migrations.AddField(
            model_name='dia',
            name='cargo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
